name: genrevibes
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#  cupertino_icons: ^0.1.3

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

  http: ^0.13.0
  cached_network_image: ^3.0.0 #2.0.0
  transparent_image: ^0.1.0
  flutter_sparkline: ^0.1.0
  shared_preferences: ^0.5.1
  flutter_villains: ^1.2.0
  share: ^0.6.5+4
#  flutter_custom_tabs: ^0.6.0
  flutter_web_browser: ^0.14.0
  persistent_bottom_nav_bar: ^2.0.0
  contained_tab_bar_view: ^0.7.0
  get: ^3.24.0
  hive: ^2.0.4 #^1.4.4+1
  hive_flutter: ^1.0.0 #^0.3.0+2
  path_provider: ^2.0.1 #^1.6.5
  jwt_decode: ^0.2.0
  adaptive_dialog: ^0.9.3
  fluttertoast: ^7.1.6
  rflutter_alert: ^1.1.0
  url_launcher: ^6.0.4 #^5.7.10
  dropdown_formfield: ^0.1.3
  flutter_masked_text: ^0.8.0
#  webfeed:
#  metadata_fetch:
#  flutter_html:
  webview_flutter:
#  xml:
  flutter_svg:
  jiffy: ^3.0.1
  recase: ^3.0.1
  chewie: ^1.0.0
  cupertino_icons: ^1.0.2
  draggable_fab: ^0.1.1
  getwidget: ^1.2.4
  sign_button: ^1.0.1
  facebook_audience_network: ^0.8.0
  google_sign_in: ^5.0.0
  flutter_facebook_auth: ^3.3.4
  dart_ipify: ^1.0.2
#  flutter_countdown_timer: ^4.1.0
  custom_timer: ^0.0.3
  awesome_dialog: ^2.1.0
  unity_ads_plugin: ^0.2.2
  in_app_review: ^2.0.2
  adcolony_flutter: ^1.4.1+1
  just_audio: ^0.7.5
  vibration: ^1.7.3
  country_codes: ^2.0.0
  flutter_pollfish: ^3.0.2
  flutter_tapjoy: ^2.0.0
  connectivity: ^3.0.6
#  trsurveys: ^1.3.0


flutter:
  uses-material-design: true
  assets:
    - images/
    - sounds/

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "images/icon/app_icon.png"

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
